### ISSUE TITLE
Missing Subtitles in Streaming mode

### ISSUE THREAD

**Issue by masterian00** [Kylart/KawAnime#54] opened 2018-12-15 05:35 UTC
I understand that the streaming service is still relatively new and would like to thank you for all the work you've put into the application so far. However, I have occasionally noticed the subtitles being mistimed or straight up missing on during streaming. The downloaded version has subtitles on the other hand. Also the sub fangroup in question is horriblesubs 1080p.

**Comment by Kylart** [comment] 2018-12-17 13:02
> I have occasionally noticed the subtitles being mistimed 

The subtitles may have a little delay (we are speaking of less than 50ms here) because it's impossible to time them at a frame accuracy which is usually the case.

> or straight up missing on during streaming.

Yes, that is something I've seen too. It's really hard to reproduce but usually it happens when rewinding the video when streaming. I don't know why this occurs though.. I'll have to investigate or change the way things work atm.

Thanks for pointing this out, I'll be on it!

**Comment by Kylart** [comment] 2019-04-16 18:37
Alright so this is fixed on the current `remake` branch, soon to be merged into `master`

**Closed by Kylart** 2019-04-16 18:37 UTC
