### ISSUE TITLE
KawAnime Server not working well

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#55] opened 2018-12-29 04:11 UTC
Dear @Kylart 
I have my vps host KawAnime as server but outside from the house 
He not playing you may check anime list over the host 
Http://185.237.96.127:49875 try to play them

**Comment by Kylart** [comment] 2018-12-30 20:19
Update on this:

So the problem is that on some web browsers, the player would not be supported for _some files_. Actually, Not all web browsers are able to read MKV files. So far, I noticed that [Firefox for example does not support it](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891), Safari either... You will be fine playing mp4 video files though!

All chromium based web browsers will work as Electron is basically a Chromium and I'm mainly developing for it. Chrome works too naturally. 

In the end, I'm going to close this issue as it's not a bug from the app but simply something that is not supported by some browsers.

**Closed by Kylart** 2018-12-30 20:19 UTC
