### ISSUE TITLE
Freezes when trying to load latest releases

### ISSUE THREAD

**Issue by DioGrando** [Kylart/KawAnime#36] opened 2018-04-17 15:05 UTC
KawAnime always freeze when it's trying to load the things in "news" section? It always says "retrying in 45 seconds" then freezes again. Is there a way to not auto-load the "new releases" section? It works fine when I remove the WiFi connection.

**Comment by Kylart** [comment] 2018-04-17 18:25
Hello,

I have several questions to be able to get you a better answer.

What do you mean be "The app freezes?" ? Like not responding at all? If so, how much RAM do your computer have?

You're saying "news" but according to what you're saying, I believe you are talking about the "release" section in which case this problem is a duplicate of #27 and #35.

I'm going to do something that will fix this for the next release.

**Comment by DioGrando** [comment] 2018-04-18 04:33
My RAM currently is 4gb (laptop). Yes, it just freezes (not responding) on the tab while it's loading the releases.

**Comment by Kylart** [comment] 2018-04-18 08:15
It should be fixed on master branch, I'll try to make a release as soon as I can!

**Closed** 2018-04-18 08:14 UTC
